"""Add phone_number to users

Revision ID: 12e593c974fd
Revises: 469d0c069a0f
Create Date: 2026-02-02 08:29:54.921817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12e593c974fd'
down_revision: Union[str, Sequence[str], None] = '469d0c069a0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True, comment='연락처 (Login ID 대용 가능)'))
    op.add_column('workers', sa.Column('user_id', sa.Integer(), nullable=False, comment='로그인 계정 ID'))
    op.add_column('workers', sa.Column('birth_date', sa.String(), nullable=True, comment='생년월일 (YYYY-MM-DD)'))
    op.add_column('workers', sa.Column('address', sa.String(), nullable=True, comment='거주지 (간략 주소)'))
    op.create_unique_constraint(None, 'workers', ['user_id'])
    op.create_foreign_key(None, 'workers', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workers', type_='foreignkey')
    op.drop_constraint(None, 'workers', type_='unique')
    op.drop_column('workers', 'address')
    op.drop_column('workers', 'birth_date')
    op.drop_column('workers', 'user_id')
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
