"""Add Project model and project_id to Site, Company, Worker

Revision ID: 1c59d0e78e71
Revises: eeafd2b1395e
Create Date: 2026-02-02 14:30:34.373067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c59d0e78e71'
down_revision: Union[str, Sequence[str], None] = 'eeafd2b1395e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False, comment='공사명 (예: OO아파트 신축공사)'),
    sa.Column('location_address', sa.String(), nullable=True, comment='공사 주소'),
    sa.Column('location_lat', sa.Float(), nullable=True, comment='위도 (지도용)'),
    sa.Column('location_lng', sa.Float(), nullable=True, comment='경도 (지도용)'),
    sa.Column('client_company', sa.String(), nullable=True, comment='발주처 (예: OO건설)'),
    sa.Column('constructor_company', sa.String(), nullable=True, comment='시공사 (예: XX종합건설)'),
    sa.Column('project_type', sa.String(), nullable=True, comment='공사 유형 (신축/리모델링/토목 등)'),
    sa.Column('budget_amount', sa.Integer(), nullable=True, comment='공사 금액 (원)'),
    sa.Column('start_date', sa.String(), nullable=True, comment='착공일 (YYYY-MM-DD)'),
    sa.Column('end_date', sa.String(), nullable=True, comment='준공 예정일 (YYYY-MM-DD)'),
    sa.Column('manager_id', sa.Integer(), nullable=True, comment='담당 소장 User ID'),
    sa.Column('safety_manager_id', sa.Integer(), nullable=True, comment='안전관리자 User ID'),
    sa.Column('status', sa.String(), nullable=True, comment='PLANNED(계획)/ACTIVE(진행 중)/DONE(완료)'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['safety_manager_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.add_column('companies', sa.Column('project_id', sa.Integer(), nullable=True, comment='소속 프로젝트 ID'))
    op.create_foreign_key(None, 'companies', 'projects', ['project_id'], ['id'])
    op.add_column('sites', sa.Column('project_id', sa.Integer(), nullable=True, comment='소속 프로젝트 ID'))
    op.create_foreign_key(None, 'sites', 'projects', ['project_id'], ['id'])
    op.add_column('workers', sa.Column('project_id', sa.Integer(), nullable=True, comment='현재 투입된 프로젝트 ID'))
    op.create_foreign_key(None, 'workers', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workers', type_='foreignkey')
    op.drop_column('workers', 'project_id')
    op.drop_constraint(None, 'sites', type_='foreignkey')
    op.drop_column('sites', 'project_id')
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.drop_column('companies', 'project_id')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
