"""Add_core_tables_v2

Revision ID: 3db90c914071
Revises: 371da63e2290
Create Date: 2026-01-29 17:18:00.925494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3db90c914071'
down_revision: Union[str, Sequence[str], None] = '371da63e2290'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False, comment='업체명'),
    sa.Column('license_no', sa.String(), nullable=True, comment='사업자등록번호'),
    sa.Column('contact', sa.String(), nullable=True, comment='현장 소장 연락처'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_table('daily_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False, comment='작업 일자'),
    sa.Column('title', sa.String(), nullable=False, comment='작업명 (예: A구역 배관 용접)'),
    sa.Column('description', sa.Text(), nullable=True, comment='작업 상세 내용'),
    sa.Column('location', sa.String(), nullable=True, comment='작업 위치'),
    sa.Column('risk_level', sa.String(), nullable=True, comment='위험도 (LOW, MEDIUM, HIGH)'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_jobs_id'), 'daily_jobs', ['id'], unique=False)
    op.create_table('danger_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False, comment='구역명'),
    sa.Column('description', sa.String(), nullable=True, comment='위험 사유'),
    sa.Column('risk_level', sa.String(), nullable=True, comment='위험 등급'),
    sa.Column('latitude', sa.Float(), nullable=False, comment='위도'),
    sa.Column('longitude', sa.Float(), nullable=False, comment='경도'),
    sa.Column('radius', sa.Float(), nullable=True, comment='반경 (미터)'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='활성화 여부'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_danger_zones_id'), 'danger_zones', ['id'], unique=False)
    op.create_table('equipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False, comment='장비명 (예: 1호기 크레인)'),
    sa.Column('type', sa.String(), nullable=False, comment='장비 타입 (CRANE, FORKLIFT, EXCAVATOR)'),
    sa.Column('status', sa.String(), nullable=True, comment='상태 (IDLE, WORKING, MAINTENANCE)'),
    sa.Column('last_inspection_date', sa.DateTime(), nullable=True, comment='마지막 점검일'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipments_id'), 'equipments', ['id'], unique=False)
    op.create_table('safety_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False, comment='카테고리 (화재, 추락, 감전 등)'),
    sa.Column('title', sa.String(), nullable=False, comment='수칙명'),
    sa.Column('description', sa.Text(), nullable=True, comment='상세 내용/가이드'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_safety_rules_id'), 'safety_rules', ['id'], unique=False)
    op.create_table('notices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False, comment='제목'),
    sa.Column('content', sa.Text(), nullable=False, comment='내용'),
    sa.Column('author_id', sa.Integer(), nullable=True, comment='작성자(관리자)'),
    sa.Column('is_important', sa.Boolean(), nullable=True, comment='중요 공지 여부'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notices_id'), 'notices', ['id'], unique=False)
    op.create_table('workers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='시스템 로그인 계정 ID (옵션)'),
    sa.Column('company_id', sa.Integer(), nullable=False, comment='소속 업체'),
    sa.Column('name', sa.String(), nullable=False, comment='성명'),
    sa.Column('job_type', sa.String(), nullable=False, comment='직종 (예: 용접공, 배관공)'),
    sa.Column('blood_type', sa.String(), nullable=True, comment='혈액형 (응급시 필요)'),
    sa.Column('years_of_experience', sa.Integer(), nullable=True, comment='경력(년)'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='재직 상태'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workers_id'), 'workers', ['id'], unique=False)
    op.create_table('attendances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False, comment='출근 기준 일자'),
    sa.Column('check_in_time', sa.DateTime(), nullable=True, comment='출근 시간'),
    sa.Column('check_out_time', sa.DateTime(), nullable=True, comment='퇴근 시간'),
    sa.Column('status', sa.String(), nullable=True, comment='PRESENT(출근), LATE(지각), EARLY_LEAVE(조퇴)'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendances_id'), 'attendances', ['id'], unique=False)
    op.create_table('job_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=True, comment='당일 역할 (예: 작업반장, 신호수)'),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['daily_jobs.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_allocations_id'), 'job_allocations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_allocations_id'), table_name='job_allocations')
    op.drop_table('job_allocations')
    op.drop_index(op.f('ix_attendances_id'), table_name='attendances')
    op.drop_table('attendances')
    op.drop_index(op.f('ix_workers_id'), table_name='workers')
    op.drop_table('workers')
    op.drop_index(op.f('ix_notices_id'), table_name='notices')
    op.drop_table('notices')
    op.drop_index(op.f('ix_safety_rules_id'), table_name='safety_rules')
    op.drop_table('safety_rules')
    op.drop_index(op.f('ix_equipments_id'), table_name='equipments')
    op.drop_table('equipments')
    op.drop_index(op.f('ix_danger_zones_id'), table_name='danger_zones')
    op.drop_table('danger_zones')
    op.drop_index(op.f('ix_daily_jobs_id'), table_name='daily_jobs')
    op.drop_table('daily_jobs')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
