"""safe_on_lite_init

Revision ID: 469d0c069a0f
Revises: 
Create Date: 2026-01-30 12:46:05.568375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '469d0c069a0f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False, comment='업체명 (예: XX건설)'),
    sa.Column('trade_type', sa.String(), nullable=True, comment='주 공종 (예: 철근, 설비)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('work_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_type', sa.String(), nullable=False, comment='작업 유형 (예: 고소작업, 용접)'),
    sa.Column('base_risk_score', sa.Integer(), nullable=True, comment='기본 위험도 점수'),
    sa.Column('required_ppe', sa.JSON(), nullable=True, comment="필수 보호구 목록 (JSON, 예: ['안전모', '안전대'])"),
    sa.Column('required_qualifications', sa.JSON(), nullable=True, comment='필수 자격 (JSON)'),
    sa.Column('checklist_items', sa.JSON(), nullable=True, comment='기본 점검 항목 리스트 (JSON)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_type')
    )
    op.create_index(op.f('ix_work_templates_id'), 'work_templates', ['id'], unique=False)
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False, comment='현장명'),
    sa.Column('address', sa.String(), nullable=True, comment='주소'),
    sa.Column('safety_manager_id', sa.Integer(), nullable=True, comment='안전관리자 User ID'),
    sa.ForeignKeyConstraint(['safety_manager_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sites_id'), 'sites', ['id'], unique=False)
    op.create_table('workers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False, comment='성명'),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('trade', sa.String(), nullable=False, comment='직종 (예: 용접공, 신호수)'),
    sa.Column('qualification_tags', sa.String(), nullable=True, comment="자격 태그 (콤마로 구분, 예: '고소작업,지게차')"),
    sa.Column('status', sa.String(), nullable=True, comment='상태: ON_SITE, OFF_SITE, RESTRICTED'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workers_id'), 'workers', ['id'], unique=False)
    op.create_table('zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(), nullable=False, comment='층/구역 (예: 1F, B1, ROOF)'),
    sa.Column('name', sa.String(), nullable=False, comment='상세 구역명 (예: A구역, E/V홀)'),
    sa.Column('type', sa.String(), nullable=False, comment='타입: INDOOR, OUTDOOR, ROOF, PIT, DANGER'),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zones_id'), 'zones', ['id'], unique=False)
    op.create_table('daily_work_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(), nullable=False, comment='YYYY-MM-DD'),
    sa.Column('description', sa.String(), nullable=True, comment='작업 내용 요약'),
    sa.Column('equipment_flags', sa.JSON(), nullable=True, comment="사용 장비 (JSON, 예: ['CRANE', 'LIFT'])"),
    sa.Column('calculated_risk_score', sa.Integer(), nullable=True, comment='계산된 위험도 점수'),
    sa.Column('status', sa.String(), nullable=True, comment='PLANNED, IN_PROGRESS, DONE'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['work_templates.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_work_plans_id'), 'daily_work_plans', ['id'], unique=False)
    op.create_table('safety_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True, comment='관련 작업 계획 ID'),
    sa.Column('log_type', sa.String(), nullable=False, comment='TRAINING(교육), INSPECTION(점검), INCIDENT(사고), NEAR_MISS(아차사고), VIOLATION(위반)'),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('photos', sa.JSON(), nullable=True, comment='사진 URL 리스트 (JSON)'),
    sa.Column('note', sa.Text(), nullable=True, comment='내용/비고'),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['daily_work_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_safety_logs_id'), 'safety_logs', ['id'], unique=False)
    op.create_table('worker_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=True, comment='당일 역할 (팀장, 작업자)'),
    sa.ForeignKeyConstraint(['plan_id'], ['daily_work_plans.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worker_allocations_id'), 'worker_allocations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_worker_allocations_id'), table_name='worker_allocations')
    op.drop_table('worker_allocations')
    op.drop_index(op.f('ix_safety_logs_id'), table_name='safety_logs')
    op.drop_table('safety_logs')
    op.drop_index(op.f('ix_daily_work_plans_id'), table_name='daily_work_plans')
    op.drop_table('daily_work_plans')
    op.drop_index(op.f('ix_zones_id'), table_name='zones')
    op.drop_table('zones')
    op.drop_index(op.f('ix_workers_id'), table_name='workers')
    op.drop_table('workers')
    op.drop_index(op.f('ix_sites_id'), table_name='sites')
    op.drop_table('sites')
    op.drop_index(op.f('ix_work_templates_id'), table_name='work_templates')
    op.drop_table('work_templates')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
