"""Add type column to companies

Revision ID: 546976069673
Revises: 1c59d0e78e71
Create Date: 2026-02-03 08:18:33.786743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '546976069673'
down_revision: Union[str, Sequence[str], None] = '1c59d0e78e71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False, comment='프로젝트 ID'),
    sa.Column('company_id', sa.Integer(), nullable=False, comment='회사 ID'),
    sa.Column('role', sa.String(), nullable=False, comment='역할 (CLIENT, CONSTRUCTOR, PARTNER)'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_participants_id'), 'project_participants', ['id'], unique=False)
    op.add_column('companies', sa.Column('type', sa.String(), nullable=True, comment='기업 구분 (GENERAL: 종합건설/발주처, SPECIALTY: 전문건설/협력사)'))
    op.alter_column('companies', 'trade_type',
               existing_type=sa.VARCHAR(),
               comment='주 공종 (예: 철근, 설비, 종합)',
               existing_comment='주 공종 (예: 철근, 설비)',
               existing_nullable=True)
    op.create_unique_constraint(None, 'companies', ['name'])
    op.drop_constraint(op.f('companies_project_id_fkey'), 'companies', type_='foreignkey')
    op.drop_column('companies', 'project_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='소속 프로젝트 ID'))
    op.create_foreign_key(op.f('companies_project_id_fkey'), 'companies', 'projects', ['project_id'], ['id'])
    op.drop_constraint(None, 'companies', type_='unique')
    op.alter_column('companies', 'trade_type',
               existing_type=sa.VARCHAR(),
               comment='주 공종 (예: 철근, 설비)',
               existing_comment='주 공종 (예: 철근, 설비, 종합)',
               existing_nullable=True)
    op.drop_column('companies', 'type')
    op.drop_index(op.f('ix_project_participants_id'), table_name='project_participants')
    op.drop_table('project_participants')
    # ### end Alembic commands ###
