"""add_hazard_columns

Revision ID: 7462b6901c83
Revises: f8175f38118a
Create Date: 2026-02-02 11:02:18.030127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7462b6901c83'
down_revision: Union[str, Sequence[str], None] = 'f8175f38118a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_work_plans', sa.Column('daily_hazards', sa.JSON(), nullable=True, comment='해당 날짜/작업의 추가 위험 요소'))
    op.add_column('zones', sa.Column('default_hazards', sa.JSON(), nullable=True, comment='해당 구역의 고정 위험 요소 목록'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zones', 'default_hazards')
    op.drop_column('daily_work_plans', 'daily_hazards')
    # ### end Alembic commands ###
