"""Add attendance table

Revision ID: a45e9c1b766f
Revises: 1997f7331379
Create Date: 2026-02-03 15:24:32.314087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a45e9c1b766f'
down_revision: Union[str, Sequence[str], None] = '1997f7331379'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='근로자 ID'),
    sa.Column('project_id', sa.Integer(), nullable=False, comment='투입된 프로젝트 ID'),
    sa.Column('date', sa.Date(), nullable=False, comment='출역일 (YYYY-MM-DD)'),
    sa.Column('check_in_time', sa.DateTime(), nullable=True, comment='출근 시간'),
    sa.Column('check_out_time', sa.DateTime(), nullable=True, comment='퇴근 시간'),
    sa.Column('check_in_method', sa.String(), nullable=True, comment='출근 인증 방식 (APP, QR, FACE, MANUAL)'),
    sa.Column('status', sa.String(), nullable=True, comment='상태 (PRESENT, LATE, LEAVE_EARLY)'),
    sa.Column('work_type_id', sa.Integer(), nullable=True, comment='당일 공종 (선택 사항)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_date'), 'attendance', ['date'], unique=False)
    op.create_index(op.f('ix_attendance_id'), 'attendance', ['id'], unique=False)
    op.create_table('notices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False, comment='제목'),
    sa.Column('content', sa.Text(), nullable=False, comment='내용'),
    sa.Column('author_id', sa.Integer(), nullable=True, comment='작성자(관리자)'),
    sa.Column('is_important', sa.Boolean(), nullable=True, comment='중요 공지 여부'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notices_id'), 'notices', ['id'], unique=False)
    op.drop_index(op.f('ix_daily_safety_info_id'), table_name='daily_safety_info')
    op.drop_table('daily_safety_info')
    op.drop_index(op.f('ix_weather_id'), table_name='weather')
    op.drop_table('weather')
    op.drop_index(op.f('ix_safety_violations_id'), table_name='safety_violations')
    op.drop_table('safety_violations')
    op.drop_index(op.f('ix_emergency_alerts_id'), table_name='emergency_alerts')
    op.drop_table('emergency_alerts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emergency_alerts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('emergency_alerts_pkey'))
    )
    op.create_index(op.f('ix_emergency_alerts_id'), 'emergency_alerts', ['id'], unique=False)
    op.create_table('safety_violations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('worker_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='위반자(User) ID'),
    sa.Column('date', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('violation_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('severity', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['users.id'], name=op.f('safety_violations_worker_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('safety_violations_pkey'))
    )
    op.create_index(op.f('ix_safety_violations_id'), 'safety_violations', ['id'], unique=False)
    op.create_table('weather',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('temperature', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('condition', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('humidity', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('wind_speed', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('weather_pkey'))
    )
    op.create_index(op.f('ix_weather_id'), 'weather', ['id'], unique=False)
    op.create_table('daily_safety_info',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_read_by_worker', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('daily_safety_info_pkey'))
    )
    op.create_index(op.f('ix_daily_safety_info_id'), 'daily_safety_info', ['id'], unique=False)
    op.drop_index(op.f('ix_notices_id'), table_name='notices')
    op.drop_table('notices')
    op.drop_index(op.f('ix_attendance_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_date'), table_name='attendance')
    op.drop_table('attendance')
    # ### end Alembic commands ###
