"""Add DailyDangerZone

Revision ID: a9b98f1cc83f
Revises: 7462b6901c83
Create Date: 2026-02-02 13:07:47.818576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9b98f1cc83f'
down_revision: Union[str, Sequence[str], None] = '7462b6901c83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_danger_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(), nullable=False, comment='YYYY-MM-DD'),
    sa.Column('risk_type', sa.String(), nullable=False, comment='HEAVY_EQUIPMENT(중장비), FIRE(화재), FALL(낙하물), ETC'),
    sa.Column('description', sa.String(), nullable=False, comment='위험 상세 (예: 이동식 크레인 작업 중)'),
    sa.Column('x', sa.Float(), nullable=True),
    sa.Column('y', sa.Float(), nullable=True),
    sa.Column('z', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_danger_zones_date'), 'daily_danger_zones', ['date'], unique=False)
    op.create_index(op.f('ix_daily_danger_zones_id'), 'daily_danger_zones', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_danger_zones_id'), table_name='daily_danger_zones')
    op.drop_index(op.f('ix_daily_danger_zones_date'), table_name='daily_danger_zones')
    op.drop_table('daily_danger_zones')
    # ### end Alembic commands ###
